## Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([2,4,5,6])
print(a*b)

#pythonda bunları for loopla yapıyoruz. numpyda direkt a*b diyerek çarpabiliyoruz

[ 2  8 15 24]


In [3]:
x = np.array([1,2,3,4])
print(type(x))

#numpy arraylerinin tipi ndarray

<class 'numpy.ndarray'>


In [4]:
y = np.zeros(10, dtype=int)
print(y)

# np.zeros 0 list oluşturur

[0 0 0 0 0 0 0 0 0 0]


In [5]:
z = np.random.normal(10,4,(3,4))
print(z)

#.normal(ortalama,standart sapma,boyut)

[[ 4.57390928 13.54935402 11.88700811 10.30826727]
 [10.76757552  3.9148037  10.9268997   8.49915633]
 [ 5.80791687  4.02857889  5.27432191 11.05001599]]


In [6]:
k = np.random.randint(0,10,size=5)
print(k)

# .random.randint(başlangıç, bitiş, size = boyut)

[0 0 9 8 8]


In [7]:
print(z.ndim)

# kaç dimensionlu olduğunu verir

2


In [8]:
print(z.shape)

# boyut bilgisi

(3, 4)


In [16]:
a.size

# eleman sayısını verir

4

In [17]:
a.dtype

# içindeki değişkenlerin tipini verir

dtype('int32')

In [19]:
u = np.random.randint(1,10,9)
u

array([4, 6, 2, 9, 8, 4, 1, 5, 3])

In [21]:
u.reshape(3,3)

# arrayın şeklini değiştirir (! uyumlu olması lazım mesela size = 10 ise 3,3 e çeviremez)

array([[4, 6, 2],
       [9, 8, 4],
       [1, 5, 3]])

In [27]:
q = np.random.randint(10, size = (3,5))
q

array([[1, 6, 3, 6, 9],
       [3, 2, 8, 2, 6],
       [9, 6, 7, 9, 3]])

In [32]:
q[2,1]

6

In [30]:
q[2][3] = 334
q

array([[  1,   6,   3,   6,   9],
       [  3,   2,   8,   2,   6],
       [  9,   6,   7, 334,   3]])

In [34]:
q[:,0]

# sadece sütün seçme

array([1, 3, 9])

In [36]:
q[0,:]

# ilk satırı seçme

array([1, 6, 3, 6, 9])

In [37]:
q[:2,3:]

# belirli parçayı alma

array([[6, 9],
       [2, 6]])

In [38]:
v = np.arange(0,30,3)
v
 
# 0 dan 30 a kadar 3 er atlayarak arr oluşturur

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [39]:
catch = [1,3,4,7]

v[catch]
 
# bu olaya(list ile birden fazla indexden value çekmek) fancy index deniyor

array([ 3,  9, 12, 21])

In [46]:
print(v[v<15])
print(v[v%2==0])

#fancy index örnekleri(içine true false arr de alabilir)

[ 0  3  6  9 12]
[ 0  6 12 18 24]


In [7]:
v = np.array([1,2,3,4,5])

print(v / 5)
print(v * 6)
print(v ** 2)
print(v - 1)

# bu şekilde manual yapılıyor
print("--------")

print(np.subtract(v,1))
print(np.add(v,1))
print(np.mean(v))
print(np.sum(v))
print(np.min(v))
print(np.max(v))
print(np.var(v))

# bu şekilde methodlarla yapılıyor


[0.2 0.4 0.6 0.8 1. ]
[ 6 12 18 24 30]
[ 1  4  9 16 25]
[0 1 2 3 4]
--------
[0 1 2 3 4]
[2 3 4 5 6]
3.0
15
1
5
2.0


In [8]:

"""
iki bilinmeyenli denklen çözümü

5x + y = 12
x + 3y = 10

"""

a = np.array([[5,1],[1,3]]) # denklemlerdeki var'ların katsayıları
b = np.array([12,10]) # denklemlerin sonuçları

np.linalg.solve(a,b) #bu method ile çözülebiliyor (linear algebra sayesinde)

array([1.85714286, 2.71428571])